repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ["--maxkb=1000"]
- repo: local
  hooks:
  - id: isort
    name: isort
    language: python
    types_or: [python, pyi]
    entry: isort
  - id: black
    name: black
    language: python
    types_or: [python, pyi]
    entry: black
  - id: flake8
    name: flake8
    language: python
    types_or: [python, pyi]
    entry: flake8
  - id: mypy
    name: mypy
    language: python
    types_or: [python, pyi]
    entry: mypy
