on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    # TODO: Should be the devcontainer.
    #container: 
    steps:
      - uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}