on: [push]

# TODO: Can we build the devcontainer image and run inside it instead?

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - uses: urgn/setup-jq-action@v3.0.2
      - run: npm install -g @devcontainers/cli

      # Run linting steps inside the devcontainer.
      # We first need to edit the devcontainer config since it's currently configured to use gpus 
      # which can't be set to be dynamically used depending on if gpus are available or not which
      # otherwise means that the container can't be started.
      - run: cat .devcontainer/devcontainer.json | jq 'del(.runArgs)' > .devcontainer/devcontainer-no-gpu.json
      - run: devcontainer up --workspace-folder . --override-config .devcontainer/devcontainer-no-gpu.json
      - run: devcontainer exec --workspace-folder . black --check .
      
      #- uses: actions/setup-python@v2
      #- run: pip install black flake8 mypy isort
      #- run: black --check .
      #- run: isort --check --diff .
      #- run: flake8 .
      #- run: mypy .

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install pytest
      - name: Run pytest
        # Pytest returns non-zero exit (5) if no tests were found so
        # we capture this case and return 0 instead.
        run: pytest . || ret=$?; [ $ret = 5 ] && exit 0 || exit $ret
